services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    container_name: avaliacoes-backend
    restart: always
    ports: 
      - "3002:3000"
    volumes:
      - ./backend/database:/app/database  # persiste o SQLite

  frontend:
    build: ./frontend
    container_name: avaliacoes-frontend
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - backend