services:
  server:
    build: ./server
    env_file:
      - ./server/.env
    container_name: avaliacoes-server
    restart: always
    ports:
      - "3002:3000"

  client:
    build: ./client
    container_name: avaliacoes-client
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - server